version: '3.7'

services:
  mysql:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=greenadmin
      - MYSQL_DATABASE=greenadmin
      - MYSQL_USER=greenadmin
      - MYSQL_PASSWORD=greenadmin
      - TZ=Asia/Shanghai
    command:
      --default_authentication_plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql_data

#  redis:
#    restart: always
#    image: redis
#    volumes:
#      - redis_data:/data

volumes:
  mysql_data: {}
