server:
  port: 9013
spring:
  thymeleaf:
    check-template: false
    check-template-location: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xfschain?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: xfschain
    password: xfschain
    initialization-mode: always
    schema: classpath:schema.sql
    continue-on-error: false

xfsgo:
  jsonrpc-http-url: ${XFSGO_JSONRPC_HTTP_URL:http://localhost:9012}