server:
  port: 8083

spring:
  thymeleaf:
    check-template: false
  profiles:
    active: dev
  datasource:
    initialization-mode: always
    schema: classpath:schema.sql
    continue-on-error: false


xfsgo:
  network-id: 1
  jsonrpc-http-url: "http://127.0.0.1:9019"