server:
  port: 8083

logging:
  level:
    com.github.binarywang.wxpay: error
    me.chanjar.weixin: error

spring:
  profiles:
    active: dev
  mvc:
    static-path-pattern: /**

#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl